### ISSUE TITLE
localhost:3000

### ISSUE THREAD

**Issue by loranger** [aschmelyun/cleaver#11]
Hello,

I just tried a fresh install, but the website does not load.
localhost:3000 _turns_ forever whereas the browsersync ui loads perfectly.

It did not tried to tweak anything, yet. It's out-of-the-box.
I cannot understand what I'm doing wrong. 
Can you help, please ?

I'm using MacOS 10.15.5 and PHP 7.4

**Comment by forsvunnet** [comment]
@loranger laravel-mix uses browsersync to proxy a local test url. The default is http://app.test/

You can change this by specifying what url browsersync should proxy.

**file: webpack.mix.js**
```

mix.browserSync({
    proxy: 'localhost:8080',
    files: [
        {
            match: ["resources/**/*"],
            fn: function(event, file) {
                command.get('php cleaver', (error, stdout, stderr) => {
                    console.log(error ? stderr : stdout);
                });
                this.reload();
            }
        }
    ]
});
```

If you have a webserver set up and configured to proxy from then you could use php as your server.

```
cd dist
php -S localhost:8080
```
