### ISSUE TITLE
Reference imports

### ISSUE THREAD

**Issue by eydun** [aschmelyun/cleaver#35]
Thank you for making this awesome tool!

I can see in the release-notes that:
`External JSON files can now be imported into content by storing them in a resources/data directory and then referencing their path in your content file's JSON (see hello-world.json for an example of this)`

I see `    "imports": "/data/example.json",` but how do I reference it in the view?

**Comment by aschmelyun** [comment]
You would reference it in the view with the `$imports` variable. So for that example with that included JSON file, you could do the following:

```php
@foreach($imports as $import)
    <a href="{{ $import->url }}">{{ $import->name }}</a>
@endforeach
```

**Comment by eydun** [comment]
Awesome, thanks!

It would be cool if it was also possible to fetch json from some remote api.
